### ISSUE TITLE
faas-flow-desc not supported in labels 

### ISSUE THREAD

**Issue by kwojcicki** [s8sg/faas-flow-tower#16]
The README.md says

```
To make flow functions visible in dashboard add the below labels in stack.yml

labels:
   faas-flow : 1
   faas-flow-desc: "option labels to provide flow descriptions"
```

If you try to deploy a function with that description the following is returnde by the faas-cli:

```
Unexpected status: 500, message: Deployment.apps "greet" is invalid: spec.template.labels: Invalid value: "option labels to provide flow descriptions": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

Probably for now the README.md can be changed to a valid value. But also I am not sure where the allowed value for spec.template.labels is defined? I assume it would be in the faas-cli repo somewhere or the faas-server repo?

**Comment by s8sg** [comment]
Ohh, it seems it was introduced on the latest version. Although I can not reproduce it.
I'm testing with: https://github.com/s8sg/branching-in-faas-flow
```bash
faas -version
Found deprecated go-style flags in command, translating to new format:
  faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  750add9e2a6d1d1f1bfb788a6a85341b4b4140e8
 version: 0.8.22

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.15.4
 sha:     a156f26443b42c3544160b68040a068150796d24
 commit:  Create tag suffix using modified arch value


Provider
 name:          faas-swarm
 orchestration: swarm
 version:       0.7.1 
 sha:           6b3410db71312d68ac77e8acd7e5aad032c6d07d
```

Can you provide the `faas -version` output

**Comment by kwojcicki** [comment]
Just tried it again and it failed when using the same label as your project

```
kwojcicki@kwojcicki-VirtualBox:~/workspace/faas-flow-test$ faas deploy -f greet.yml
Deploying: pipeline.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Unexpected status: 500, message: Deployment.apps "pipeline" is invalid: spec.template.labels: Invalid value: "flow for a example braching execution": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

Function 'pipeline' failed to deploy with status code: 500
kwojcicki@kwojcicki-VirtualBox:~/workspace/faas-flow-test$ 
kwojcicki@kwojcicki-VirtualBox:~/workspace/faas-flow-test$ 
kwojcicki@kwojcicki-VirtualBox:~/workspace/faas-flow-test$ OPENFAAS_URL=10.192.0.2:31112 faas -version
Found deprecated go-style flags in command, translating to new format:
  faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  5fcdc692e4adf04977775ea78f79b3534a44fb36
 version: 0.8.21

Gateway
 uri:     http://10.192.0.2:31112
 version: 0.15.0
 sha:     4c12c2e2f8f3f4b4bfd740afee628d8b5524230c
 commit:  Add tests for loading the logs provider value from the env


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.8.1 
 sha:           ba1e9488db9a31aeec86a773537ac9d9802e6482
```

**Comment by kwojcicki** [comment]
Updated my CLI and I still get the same problem

```
kwojcicki@kwojcicki-VirtualBox:~/workspace/faas-flow-test$ faas deploy -f greet.yml
Deploying: pipeline.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Unexpected status: 500, message: Deployment.apps "pipeline" is invalid: spec.template.labels: Invalid value: "flow for a example braching execution": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

Function 'pipeline' failed to deploy with status code: 500
kwojcicki@kwojcicki-VirtualBox:~/workspace/faas-flow-test$ OPENFAAS_URL=10.192.0.2:31112 faas -version
Found deprecated go-style flags in command, translating to new format:
  faas version
  ___                   _____           ____
 / _ \ _ __   ___ _ __ |  ___|_ _  __ _/ ___|
| | | | '_ \ / _ \ '_ \| |_ / _` |/ _` \___ \
| |_| | |_) |  __/ | | |  _| (_| | (_| |___) |
 \___/| .__/ \___|_| |_|_|  \__,_|\__,_|____/
      |_|

CLI:
 commit:  750add9e2a6d1d1f1bfb788a6a85341b4b4140e8
 version: 0.8.22

Gateway
 uri:     http://10.192.0.2:31112
 version: 0.15.0
 sha:     4c12c2e2f8f3f4b4bfd740afee628d8b5524230c
 commit:  Add tests for loading the logs provider value from the env


Provider
 name:          faas-netes
 orchestration: kubernetes
 version:       0.8.1 
 sha:           ba1e9488db9a31aeec86a773537ac9d9802e6482
```

**Comment by kwojcicki** [comment]
This is what my greet.yml looks like 

```
version: 1.0
provider:
  name: openfaas
  gateway: http://10.192.0.2:31112
functions:
  pipeline:
    lang: faas-flow
    handler: ./greet
    image: greet:latest
    environment:
      read_timeout: 120 # A value larger than `max` of all execution times of Nodes
      write_timeout: 120 # A value larger than `max` of all execution times of Nodes
      write_debug: true
      combine_output: false
      workflow_name: "greet" # The name of the flow function, faasflow use this to forward completion event
    environment_file:
      - flow.yml
    labels:
      faas-flow : 1
      faas-flow-desc: "flow for a example braching execution"
```
