### ISSUE TITLE
Add Health Check for Dashboard

### ISSUE THREAD

**Issue by chennqqi** [s8sg/faas-flow-tower#3]
for kubenets

**Comment by s8sg** [comment]
Please provide more details

**Comment by chennqqi** [comment]
![image](https://user-images.githubusercontent.com/5073720/59755518-9ef5ec00-92ba-11e9-899c-3c93861b6ed1.png)
according
https://docs.openfaas.com/reference/workloads/#common-properties
```
On Swarm:

create a lock file in /tmp/.lock - removing this file signals service degradation
add a HEALTHCHECK instruction if using Docker Swarm
On Kubernetes:

or enable httpProbe in the helm chart and implement /_/health as a HTTP endpoint
create a lock file in /tmp/.lock - removing this file signals service degradation
```

if health check failed, pod' status will change to `CrashLoopBackOff`
![image](https://user-images.githubusercontent.com/5073720/59755885-496e0f00-92bb-11e9-9531-909e1d49700b.png)
`

**Comment by s8sg** [comment]
I'm confused. So Openfaas watchdog doesn't provide the health check endpoint ?
```yaml
    annotations:
      com.openfaas.health.http.path: "/healthz"
      com.openfaas.health.http.initialDelay: "30s"
```
